language: node_js
node_js:
  - "lts/*"

script:
  - npm test

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "lts/*"
      script:
        - npm test
        - npm run docs
        - ./scripts/build.sh
      before_deploy:
        - |
          function npm_dist_tag() {
            if [[ "$TRAVIS_TAG" = *"-"* ]]; then
              echo "beta"
            else
              echo "latest"
            fi
          }
        - cd ./dist
      deploy:
        - provider: npm
          email: "$NPM_EMAIL"
          api_key: "$NPM_TOKEN"
          skip_cleanup: true
          tag: $(npm_dist_tag)
          on:
            tags: true
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
          keep_history: true
          local_dir: ./docs
          on:
            tags: true
            branch: master
